pull_request_rules:
  - name: Automated dependabot merge
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=lint
      - status-success=Vercel
    actions:
      merge:
        method: merge
